### ISSUE TITLE
Cleanup existing state

### ISSUE THREAD

**Issue by gargol** [NexesJS/mongo-knex#2]
Get up to date with the state of mongo-knex.

- [x] take a look at the test framework & merge test framework (https://github.com/NexesJS/mongo-knex/pull/1) - do not take a look at all tests (!)
- [x] research what's already done in joins branch and come up with a conclusion if it's helpful ( https://github.com/NexesJS/mongo-knex/tree/joins ) - write down the conclusion as comment (!)

**Comment by kirrg001** [comment]
> research what's already done in joins branch and come up with a conclusion if it's helpful ( https://github.com/NexesJS/mongo-knex/tree/joins ) - write down the conclusion as comment (!)

I had a look at the implementation. IMO the implementation does not use the correct strategy described in https://github.com/NexesJS/NQL/issues/1. The PR instead uses [joins and group by](https://github.com/NexesJS/mongo-knex/commit/e136a6f52cd3bf43701d6dd6c6b43e24638f6f8f#diff-8ed5262100dab197d3b7fa273ca3e105R135), which does not work for all cases, because it does not look at each individual relation. 

No need to remove the PR yet, we can still use it as a lookup reference 👍 It might be helpful to lookup/steal/copy the structure of the code :)

**Comment by gargol** [comment]
@kirrg001 but we still want to use the testing framework even though the strategy will be different, right?

**Comment by kirrg001** [comment]
@gargol Yeah sure 👍
